/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author samsung
 */
import dao.VoitureDAO;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import models.Voiture;
public class AjouterVoitureFrame extends javax.swing.JFrame {
    // Custom constructors
    public AjouterVoitureFrame() {
        initComponents();
        setupFrame("Ajouter un Véhicule");
        setupEnterKeyNavigation();
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/resources/jmlogo.png")).getImage());
        setResizable(false); 
    }

    /**
     * Creates new form AjouterVoitureFrame
     */
    public AjouterVoitureFrame(Voiture voiture) {
        initComponents();
        setupFrame("Modifier Véhicule");
        setupEnterKeyNavigation();
        populateFields(voiture);
        this.originalPlaque = voiture.getPlaqueImmatriculation();
    }
    private String originalPlaque;
    private void setupFrame(String title) {
    setTitle(title);
    setLocationRelativeTo(null);
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    
    // Make sure text fields are editable only in add mode
    txtPlaque.setEditable(originalPlaque == null);
}

    private void populateFields(Voiture v) {
        txtPlaque.setText(v.getPlaqueImmatriculation());
        txtMarque.setText(v.getMarque());
        txtModel.setText(v.getModele());
        txtAnnee.setText(String.valueOf(v.getAnnee()));
        txtCouleur.setText(v.getCouleur());
        txtKilometrage.setText(String.valueOf(v.getKilometrage()));
        txtDernierVidange.setText(String.valueOf(v.getDernierVidange()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPlaque = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtKilometrage = new javax.swing.JTextField();
        txtMarque = new javax.swing.JTextField();
        txtDernierVidange = new javax.swing.JTextField();
        BTN_Annuler = new javax.swing.JButton();
        BTN_ENG = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAnnee = new javax.swing.JTextField();
        txtCouleur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ajouter/Modifier Voiture");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Plaque");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Marque");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Dernière vidange");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Kilométrage");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Modèle");

        txtPlaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaqueActionPerformed(evt);
            }
        });

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtKilometrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilometrageActionPerformed(evt);
            }
        });

        txtMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarqueActionPerformed(evt);
            }
        });

        txtDernierVidange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDernierVidangeActionPerformed(evt);
            }
        });

        BTN_Annuler.setBackground(new java.awt.Color(204, 204, 204));
        BTN_Annuler.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BTN_Annuler.setText("Annuler");
        BTN_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AnnulerActionPerformed(evt);
            }
        });

        BTN_ENG.setBackground(new java.awt.Color(204, 204, 204));
        BTN_ENG.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BTN_ENG.setText("Enregistrer");
        BTN_ENG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ENGActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("KM");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("KM");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Année");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Couleur");

        txtAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnneeActionPerformed(evt);
            }
        });

        txtCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCouleurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtDernierVidange))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(60, 60, 60)
                                        .addComponent(txtKilometrage))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(BTN_ENG, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTN_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(94, 94, 94)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPlaque, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMarque, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(6, 6, 6)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(txtPlaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKilometrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDernierVidange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_ENG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlaqueActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtKilometrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilometrageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrageActionPerformed

    private void txtMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarqueActionPerformed

    private void txtDernierVidangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDernierVidangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDernierVidangeActionPerformed

    private void BTN_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AnnulerActionPerformed
        // TODO add your handling code here:
        this.dispose(); // Close current window
        new GestionDesVoituresFrame().setVisible(true); // Reopen main menu
    }//GEN-LAST:event_BTN_AnnulerActionPerformed

    private void BTN_ENGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ENGActionPerformed
        // TODO add your handling code here:
         try {
        // 1. Validate all fields first
        validateFields();
        
        // 2. Create vehicle object
        Voiture v = new Voiture(
            txtPlaque.getText().trim().toUpperCase(),
            txtMarque.getText().trim(),
            txtModel.getText().trim(),
            Integer.parseInt(txtAnnee.getText().trim()),
            txtCouleur.getText().trim(),
            Integer.parseInt(txtKilometrage.getText().trim()),
            Integer.parseInt(txtDernierVidange.getText().trim())
        );

        // 3. Check for duplicate plaque (only in add mode)
        if (originalPlaque == null && VoitureDAO.vehicleExists(v.getPlaqueImmatriculation())) {
            throw new IllegalArgumentException("Une voiture avec cette plaque existe déjà");
        }

        // 4. Save or update
        if (originalPlaque == null) {
            VoitureDAO.addVoiture(v);
            showSuccess("Véhicule ajouté avec succès!");
        } else {
            VoitureDAO.modifierVoiture(originalPlaque, v);
            showSuccess("Véhicule modifié avec succès!");
        }
        
        this.dispose();
        new GestionDesVoituresFrame().setVisible(true);
        
    } catch (NumberFormatException e) {
        showError("Valeur numérique invalide", "Veuillez entrer un nombre valide pour:\n"
            + (txtAnnee.getText().isEmpty() ? "- Année\n" : "")
            + (txtKilometrage.getText().isEmpty() ? "- Kilométrage\n" : "")
            + (txtDernierVidange.getText().isEmpty() ? "- Dernière vidange" : ""));
    } catch (IllegalArgumentException e) {
        showError("Données invalides", e.getMessage());
    } catch (SQLException e) {
        showError("Erreur de base de données", "Une erreur est survenue:\n" + e.getMessage());
    }
    }//GEN-LAST:event_BTN_ENGActionPerformed

    private void txtAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnneeActionPerformed

    private void txtCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCouleurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCouleurActionPerformed
    // In your AjoutVoitureFrame constructor or initialization method:
    private void validateFields() throws IllegalArgumentException {
    // Check required fields
    if (txtPlaque.getText().trim().isEmpty()) {
        txtPlaque.requestFocus();
        throw new IllegalArgumentException("La plaque est obligatoire");
    }
    
    if (txtMarque.getText().trim().isEmpty()) {
        txtMarque.requestFocus();
        throw new IllegalArgumentException("La marque est obligatoire");
    }
    
    if (txtModel.getText().trim().isEmpty()) {
        txtModel.requestFocus();
        throw new IllegalArgumentException("Le modèle est obligatoire");
    }
    
    // Validate numeric fields
    try {
        int annee = Integer.parseInt(txtAnnee.getText().trim());
        if (annee < 1900 || annee > java.time.Year.now().getValue()) {
            throw new IllegalArgumentException("L'année doit être entre 1900 et " + java.time.Year.now().getValue());
        }
    } catch (NumberFormatException e) {
        txtAnnee.requestFocus();
        throw new IllegalArgumentException("L'année doit être un nombre valide");
    }
    
    try {
        int km = Integer.parseInt(txtKilometrage.getText().trim());
        if (km < 0) throw new IllegalArgumentException("Le kilométrage ne peut pas être négatif");
    } catch (NumberFormatException e) {
        txtKilometrage.requestFocus();
        throw new IllegalArgumentException("Le kilométrage doit être un nombre valide");
    }
    
    try {
        int dernierVidange = Integer.parseInt(txtDernierVidange.getText().trim());
        int kilometrage = Integer.parseInt(txtKilometrage.getText().trim());
        if (dernierVidange > kilometrage) {
            throw new IllegalArgumentException("Le dernier vidange ne peut pas être supérieur au kilométrage actuel");
        }
    } catch (NumberFormatException e) {
        txtDernierVidange.requestFocus();
        throw new IllegalArgumentException("Le dernier vidange doit être un nombre valide");
    }
}

// Improved message dialogs
private void showError(String title, String message) {
    JOptionPane.showMessageDialog(this, 
        "<html><b>" + title + "</b><br>" + message.replace("\n", "<br>") + "</html>", 
        "Erreur", 
        JOptionPane.ERROR_MESSAGE);
}

private void showSuccess(String message) {
    JOptionPane.showMessageDialog(this, 
        "<html><b>Succès!</b><br>" + message + "</html>", 
        "Opération réussie", 
        JOptionPane.INFORMATION_MESSAGE);
}
private void setupEnterKeyNavigation() {
    // List of all your text fields in order
    JTextField[] fields = {
        txtPlaque, txtMarque, txtModel, txtKilometrage, txtDernierVidange
    };
    
    for (int i = 0; i < fields.length; i++) {
        final int currentIndex = i;
        fields[i].addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    // If not last field, go to next field
                    if (currentIndex < fields.length - 1) {
                        fields[currentIndex + 1].requestFocus();
                    } else {
                        // If last field, trigger the save action
                        BTN_ENG.doClick();
                    }
                    e.consume(); // Prevent the "ding" sound
                }
            }
        });
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterVoitureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterVoitureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterVoitureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterVoitureFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterVoitureFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Annuler;
    private javax.swing.JButton BTN_ENG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAnnee;
    private javax.swing.JTextField txtCouleur;
    private javax.swing.JTextField txtDernierVidange;
    private javax.swing.JTextField txtKilometrage;
    private javax.swing.JTextField txtMarque;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlaque;
    // End of variables declaration//GEN-END:variables
}
