/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author samsung
 */
public class MainMenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame() {
        initComponents();
        setTitle("Menu Principale");
        setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/resources/jmlogo.png")).getImage());
        setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BTN_Assurance = new javax.swing.JButton();
        BTN_QUITTER = new javax.swing.JButton();
        BTN_GLesVoitures = new javax.swing.JButton();
        BTN_AlertEntr = new javax.swing.JButton();
        BTN_SortieVoitures = new javax.swing.JButton();
        BTN_Contrat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setBackground(new java.awt.Color(51, 153, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU GESTION JM CARS ");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/jm logo black (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(47, 47, 47))
        );

        BTN_Assurance.setBackground(new java.awt.Color(204, 204, 204));
        BTN_Assurance.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        BTN_Assurance.setText("GESTION DES CONTROLLE TECHNIQUE");
        BTN_Assurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AssuranceActionPerformed(evt);
            }
        });

        BTN_QUITTER.setBackground(new java.awt.Color(204, 204, 204));
        BTN_QUITTER.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTN_QUITTER.setText("QUITTER");
        BTN_QUITTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_QUITTERActionPerformed(evt);
            }
        });

        BTN_GLesVoitures.setBackground(new java.awt.Color(204, 204, 204));
        BTN_GLesVoitures.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTN_GLesVoitures.setText("GERER LES VOITURES");
        BTN_GLesVoitures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GLesVoituresActionPerformed(evt);
            }
        });

        BTN_AlertEntr.setBackground(new java.awt.Color(204, 204, 204));
        BTN_AlertEntr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTN_AlertEntr.setText("GESTION DES ALERTES");
        BTN_AlertEntr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AlertEntrActionPerformed(evt);
            }
        });

        BTN_SortieVoitures.setBackground(new java.awt.Color(204, 204, 204));
        BTN_SortieVoitures.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTN_SortieVoitures.setText("GESTION SORTIE DES VOITURES");
        BTN_SortieVoitures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SortieVoituresActionPerformed(evt);
            }
        });

        BTN_Contrat.setBackground(new java.awt.Color(204, 204, 204));
        BTN_Contrat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BTN_Contrat.setText("GESTION DES CONTRATS");
        BTN_Contrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ContratActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_Assurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_AlertEntr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_GLesVoitures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_SortieVoitures)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BTN_QUITTER, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Contrat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_GLesVoitures, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_SortieVoitures, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_AlertEntr, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Contrat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_Assurance, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_QUITTER, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_GLesVoituresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GLesVoituresActionPerformed
            // TODO add your handling code here:
            System.out.println("Ouvrir la gestion des véhicules...");
            new GestionDesVoituresFrame().setVisible(true);
            this.dispose(); 
    }//GEN-LAST:event_BTN_GLesVoituresActionPerformed

    private void BTN_QUITTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_QUITTERActionPerformed
        // TODO add your handling code here:
        int choix = JOptionPane.showConfirmDialog(
        this,
        "Voulez-vous vraiment quitter l'application?",
        "Confirmation",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    
    if (choix == JOptionPane.YES_OPTION) {
        System.exit(0);
    }// Close the app
    }//GEN-LAST:event_BTN_QUITTERActionPerformed

    private void BTN_AlertEntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AlertEntrActionPerformed
        // TODO add your handling code here:
        new AlertsFrame().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_BTN_AlertEntrActionPerformed

    private void BTN_AssuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AssuranceActionPerformed
        // TODO add your handling code here:
        new ControlleTechniqueFrame().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_BTN_AssuranceActionPerformed

    private void BTN_SortieVoituresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SortieVoituresActionPerformed
        // TODO add your handling code here:
        new SortieVoitureFrame().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_BTN_SortieVoituresActionPerformed

    private void BTN_ContratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ContratActionPerformed
        // TODO add your handling code here:
        new GestionDesContrats().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTN_ContratActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_AlertEntr;
    private javax.swing.JButton BTN_Assurance;
    private javax.swing.JButton BTN_Contrat;
    private javax.swing.JButton BTN_GLesVoitures;
    private javax.swing.JButton BTN_QUITTER;
    private javax.swing.JButton BTN_SortieVoitures;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
